# name: Node App CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: Node App Environment

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: SSH & Deploy
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_KEY }}
#           script: |
#             cd /home/ubuntu/cicd-project     
#             git pull origin main 
#             npm install 
#             pm2 stop app || true 
#             pm2 start app.js --name app 


name: Node App CI/CD

on:
  push:
    branches:
      - main

jobs:

  # JOB 1: Build + Test + Sonar
  build:
    runs-on: ubuntu-latest
    environment: Node App Environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # - name: Run tests with coverage
      #   run: npm test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=kartik-thynqit_node-app-v2
            -Dsonar.organization=kartik-thynqit
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Check Quality Gate
      #   uses: SonarSource/sonarcloud-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # JOB 2: Deploy (only if build passes)
  deploy:
    needs: build   
    runs-on: ubuntu-latest
    environment: Node App Environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/cicd-project     
            git pull origin main 
            npm install 
            pm2 stop app || true 
            pm2 start app.js --name app 